definitions:
  models.CreateUser:
    properties:
      email:
        type: string
      username:
        type: string
    required:
    - email
    - username
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    required:
    - email
    - username
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/models.User'
                type: array
              message:
                type: string
              status:
                type: integer
            type: object
      summary: Get all users
      tags:
      - Users
      x-order: 1
    post:
      consumes:
      - application/json
      description: Create users
      parameters:
      - description: Request Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                $ref: '#/definitions/models.User'
              message:
                type: string
              status:
                type: integer
            type: object
      summary: Create users
      tags:
      - Users
      x-order: 3
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Users By Key
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                type: string
              status:
                type: integer
            type: object
      summary: Delete Users By Key
      tags:
      - Users
      x-order: 4
    get:
      consumes:
      - application/json
      description: Get Users By Key
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                type: string
              status:
                type: integer
            type: object
      summary: Get Users By Key
      tags:
      - Users
      x-order: 2
swagger: "2.0"
