info:
  contact: {}
paths:
  /healthCheck:
    get:
      description: Checks the health of the server
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - Health Check
swagger: "2.0"
